---
title: "Final Project Proposal"
output: github_document
date: "2024-11-06"
---

## Project Title
**Voting in Crisis: Analyzing the Impact of COVID-19 on the 2020 Election in New York State**

## Group member

Li Jiang (lj2607), Tiancheng Shi (ts3593), Yifei Chen (yc4587), Yue Ge (yg3040)

## motivation for this project
The 2020 U.S. election occurred under the shadow of the COVID-19 pandemic, impacting voter turnout and behavior. This project aims to analyze correlations between COVID-19 case/death rates, voter demographics, and election results in New York State, offering insights into how health crises affect democratic processes.

## Intended final products
**Interactive Map**: Heatmaps showing COVID-19 death density and correlations with voter turnout, along with trend graphs displaying voter turnout over time.\
**Comprehensive Report**: Summary of key findings, statistical analyses, and policy recommendations for future crisis-resilient elections.\
**Project Website**: A public-facing site hosting the dashboard, report, data sources, methodology, and insights.\
**Screencast**: Short videos presenting the research questions, data analysis, and main conclusions.\

## Data Sources
**Election Results**: 2020 presidential election results from the NY State Board of Elections and NYC Open Data.\
**COVID-19 Data**: Case/death counts, testing rates, and positivity rates from the NYC Department of Health.\
**Demographic Data**: U.S. Census data for age, income, and racial demographics.\
**Socioeconomic Indicators**: Data on income and unemployment from the Bureau of Labor Statistics.\
**Public Health Infrastructure**: Data on healthcare facility locations from NYC OpenData. \

## Planned analyses / visualizations / coding challenges
**Correlation and Regression Analysis**: Identify relationships between COVID-19 rates and voter turnout, examining demographic and socioeconomic influences.\
**Trend Analysis**: Overlay COVID-19 trends with voter turnout.\
**Geospatial Visualization**: Create heatmaps of COVID-19 impacts and voter turnout.\
**Coding Challenges**: Manage multi-format datasets, create geospatial visualizations, and develop an interactive dashboard.\

## Timeline
**Nov 6 - Nov 19**: Data collection and cleaning.\
**Nov 20 - Nov 26**: Exploratory Data Analysis (EDA).\
**Nov 27 - Dec 3**: Regression modeling and analysis.\
**Dec 4 - Dec 6**: Visualization creation.\
**Dec 7 - Dec 8**: Finalization and submission of deliverables.\